# Generated by Django 4.1.7 on 2023-04-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_no', models.IntegerField()),
                ('d_name', models.CharField(max_length=50)),
                ('loc', models.CharField(max_length=50)),
            ],
        ),
    ]
