# Generated by Django 4.1.7 on 2023-04-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('emp_no', models.IntegerField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('mgr', models.IntegerField()),
                ('hirdate', models.DateField()),
                ('sal', models.IntegerField()),
                ('comm', models.IntegerField()),
                ('dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.department')),
            ],
        ),
    ]
