# Generated by Django 4.1.7 on 2023-04-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='comm',
            field=models.BooleanField(null=True),
        ),
    ]
